-- 대장균의 크기에 따라 분류하기 2

/* PERCENT_RANK 윈도우 함수 사용 */
SELECT ID, (CASE
            WHEN PER_COLONY <= 0.25 THEN 'CRITICAL'
            WHEN PER_COLONY <= 0.5 THEN 'HIGH'
            WHEN PER_COLONY <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
           END) AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS PER_COLONY
      FROM ECOLI_DATA) E
ORDER BY ID;
