-- 대장균들의 자식의 수 구하기

SELECT E.ID, IF(P.CHILD_COUNT IS NULL, 0, P.CHILD_COUNT) AS CHILD_COUNT
FROM ECOLI_DATA E LEFT JOIN (SELECT IF(PARENT_ID IS NULL, 0, PARENT_ID) AS ID, COUNT(*) AS CHILD_COUNT
                             FROM ECOLI_DATA
                             GROUP BY PARENT_ID) P
     ON E.ID = P.ID
ORDER BY ID;
