-- 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기

WITH MAX_VIEWS As (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM MAX_VIEWS M LEFT JOIN USED_GOODS_FILE F
    ON M.BOARD_ID = F.BOARD_ID
ORDER BY FILE_ID DESC;
