-- 카테고리 별 도서 판매량 집계하기

SELECT CATEGORY, SUM(SALES) as TOTAL_SALES
FROM BOOK_SALES S LEFT JOIN BOOK B
    ON(S.BOOK_ID = B.BOOK_ID)
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY;