-- 상품 별 오프라인 매출 구하기

SELECT P.PRODUCT_CODE, P.PRICE*SUM(O.SALES_AMOUNT) as SALES
FROM OFFLINE_SALE O LEFT JOIN PRODUCT P
    ON(O.PRODUCT_ID = P.PRODUCT_ID)
GROUP BY P.PRODUCT_CODE
ORDER BY SALES desc, PRODUCT_CODE asc;