-- 5월 식품들의 총매출 조회하기

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT*P.PRICE) as TOTAL_SALES
FROM FOOD_ORDER O LEFT JOIN FOOD_PRODUCT P
    ON(O.PRODUCT_ID = P.PRODUCT_ID)
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES desc, PRODUCT_ID asc;