-- 그룹별 조건에 맞는 식당 목록 출력하기

WITH COUNT_REVIEW AS (
    SELECT COUNT(REVIEW_ID) AS CNT, MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), -- WITH 구문은 콤마로 여러개 작성할 수 있음

MAX_MEMBER AS (
    SELECT MEMBER_ID
    FROM COUNT_REVIEW
    WHERE CNT = (SELECT MAX(CNT) FROM COUNT_REVIEW)
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R 
LEFT JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_MEMBER)
ORDER BY REVIEW_DATE, REVIEW_TEXT;
