-- 년, 월, 성별 별 상품 구매 회원 수 구하기

SELECT YEAR(S.SALES_DATE) as YEAR, 
       MONTH(S.SALES_DATE) as MONTH, 
       U.GENDER, 
       COUNT(DISTINCT S.USER_ID) as USERS -- 회원 수를 구하고 있기 때문에 중복 제거
FROM ONLINE_SALE S LEFT JOIN USER_INFO U
    ON(S.USER_ID = U.USER_ID)
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), U.GENDER
ORDER BY YEAR, MONTH, GENDER;
