-- 보호소에서 중성화한 동물

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I
    ON(O.ANIMAL_ID = I.ANIMAL_ID)
WHERE I.SEX_UPON_INTAKE IN('Intact Male', 'Intact Female')
  AND O.SEX_UPON_OUTCOME IN('Neutered Male', 'Spayed Female');