-- 우유와 요거트가 담긴 장바구니

/* GROUP_CONCAT() 함수 사용 */
SELECT CART_ID
FROM CART_PRODUCTS
GROUP BY CART_ID
HAVING GROUP_CONCAT(NAME) LIKE '%Milk%' 
   AND GROUP_CONCAT(NAME) LIKE '%Yogurt%'
ORDER BY CART_ID;
