-- 취소되지 않은 진료 예약 조회하기

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A 
    LEFT JOIN PATIENT P ON(A.PT_NO = P. PT_NO)
    LEFT JOIN DOCTOR D ON(A.MDDR_ID = D.DR_ID)
WHERE DATE(APNT_YMD) = '2022-04-13'
    AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;