-- 특정 세대의 대장균 찾기

WITH ECOLI_DATA_THIRD AS (
    SELECT F.ID AS FIRST, F.PARENT_ID AS SECOND, S.PARENT_ID AS THIRD
    FROM ECOLI_DATA F LEFT JOIN ECOLI_DATA S
        ON F.PARENT_ID = S.ID
)

SELECT T.FIRST AS ID
FROM ECOLI_DATA_THIRD T LEFT JOIN ECOLI_DATA F
    ON T.THIRD = F.ID
WHERE T.THIRD IS NOT NULL AND F.PARENT_ID IS NULL
ORDER BY ID;
